### ISSUE TITLE
Unable to upload transaction: 400, Request type not found.

### ISSUE THREAD

**Issue by daweth** [ArweaveTeam/arweave-js#103]
## Issue:

When calling the `uploader.uploadChunk()` function, this error is produced. This is following the tutorial code for uploading a file using chunks.

**Comment by DNisch** [comment]
I had the same problem. "400, Request type not found." seems to be issued in general for many things. I found this solution that works for me in the depths of the arweave dev discord:

I had the following code from the README:
`const arweave = Arweave.init({ host: 'arweave.net' });`

I replaced it with this:
`const arweave = Arweave.init({ host: 'arweave.net', protocol: 'https', port: 443 });`

**Comment by daweth** [comment]
@DNisch Incredible!!! that did the trick.
