### ISSUE TITLE
Export Transaction class

### ISSUE THREAD

**Issue by 0xDjole** [ArweaveTeam/arweave-js#104]
I need Transaction class to be exported.

**Comment by mcmonkeys1** [comment]
can you fork your own copy and export it then?

**Comment by 0xDjole** [comment]
Sure, will it be merged back?

**Comment by rosmcmahon** [comment]
what is your need to have Transaction exported?

**Comment by rosmcmahon** [comment]
closing as appears stale. feel free to reopen.
