### ISSUE TITLE
getData returns empty string for larger files

### ISSUE THREAD

**Issue by 0xDjole** [ArweaveTeam/arweave-js#105]
So I am trying to save and get the image of 415kb. That works fine. I get status 200.

When I try to get data, I use getData function and I get back empty string.

Just replacing that image with 11kb image for example, works fine.

Is there a different method I need to use? From doc it says it supports larger uploads... 

I use testweave-sdk. Could that be the issue that it doesn't return it?

**Comment by rosmcmahon** [comment]
are you still experiencing this issue? perhaps we can troubleshoot with you in the Discord server. 

[Arweave Dev Discord Server](https://discord.gg/GMywYK5q)

closing this issue for now.
