### ISSUE TITLE
[Bug] - Typo in Docs 

### ISSUE THREAD

**Issue by doswelleth** [ArweaveTeam/arweave-js#110]
The word [separately](https://github.com/doswelleth/arweave-js/pull/1) under `Transactions`

<img width="264" alt="Screen Shot 2021-10-15 at 5 29 33 PM" src="https://user-images.githubusercontent.com/25995735/137566673-a508a56b-8bb2-4779-b4e4-4b6aedc2f5f2.png">

**Comment by rosmcmahon** [comment]
fixed that for you, thanks!
