### ISSUE TITLE
Block for 5 seconds then "Uncaught (in Promise) Error" in Transactions.sign for files >5MB

### ISSUE THREAD

**Issue by ashleyrudland** [ArweaveTeam/arweave-js#111]
### Environment:

```
Chrome: 94.0.4606.81
AR Connect Extension: 0.3.5
AR Balance in Wallet: 4.51 AR ($233)
```

### Packages:
```
arweave: 1.10.18
react-scripts: 4.0.3
react: 17.0.2
typescript: 4.1.5
```

### Purpose:
I'm building a decentralised version of YouTube, our platform uploads thumbnails and MP4 videos (multiple GBs in size) straight to ARWeave using the `arweave-js` package running in the browser in our React web app. I want to go live in coming weeks and I am currently blocked due to this issue.

### Description of issue:
Any file I upload above 5MB causes `await arweave.transactions.sign(transaction)` to block for around 5 seconds, then throws the following Unhandled Exception in the console:

`Uncaught (in promise) Error: Message length exceeded maximum allowed length.`

This is clearly not the actual error, I've debugged the internal source code of `arweave-js` and I cannot find where things are failing.

<img width="814" alt="Screenshot 2021-10-15 at 15 07 52" src="https://user-images.githubusercontent.com/3226237/137640648-89d441c2-9d2d-4fcc-b8a8-ec853ceec9e6.png">

### Code: 
```typescript
const transaction = await arweave.createTransaction({ data: file })
transaction.addTag('Content-Type', 'video/mp4') 

await arweave.transactions.sign(transaction)
```
* the `file` is an `ArrayBuffer` of the MP4

### Other important info / thoughts
* Any file under 5MB works without any issues (I see the confetti 😂)
* If I modify the code to use a local AR node and generate a fresh wallet, this also works for any file size
* Yes, I have enough in my wallet 😁, just over $233 worth of AR. I've gone through this process around 40 times to make sure I'm not making a dumb mistake before posting this issue :-)

Really hope you all can help :)

**Comment by rosmcmahon** [comment]
I would think this is an issue with ArConnect in that case... Let's check with them
