### ISSUE TITLE
Confusing code in Merkle.ts file for buildLayers and hashBranch functions

### ISSUE THREAD

**Issue by jsoneaday** [ArweaveTeam/arweave-js#113]
Hello in the buildLayers function, the very first if statement checks that the node.length is less than 2. Only 1 and 0 is less than 2 and yet the call to hashBranch takes two node parameters. If the length is 0 this would fail. If the length is 1 this would also fail because hashBranch takes two non-nullable parameters.

Next issue is in hashBranch itself. First an if statement runs to see if right node is null and then if true it returns a casted BranchNode. This is an issue because the function generateTransactionChunks first calls generateLeaves, which of course returns leaves, and then passes those leaves to the buildLayers function. If the leaves nodes is less than two then buildLayers call to hashBranch goes to the if statement at the top which casts the node into a BranchNode, but the node is not a BranchNode it is a LeafNode. Later in other parts of code if this node is called as a BranchNode it will fail.

**Comment by rosmcmahon** [comment]
and yet it works :-D 
I agree that some of the code would not seem to make 100% logical sense or be the most efficient. a PR to clean up the code is welcome!

**Comment by jsoneaday** [comment]
Thanks!

**Comment by rosmcmahon** [comment]
i started fixing this btw. buildLayers should make more sense now?

**Comment by jsoneaday** [comment]
Terrific now all you need to so is a Swift Api! Haha

**Comment by rosmcmahon** [comment]
Loool

**Comment by rosmcmahon** [comment]
closing this, feel free to reopen if you have anything further to add
