### ISSUE TITLE
Invalid data_root does not fail transaction

### ISSUE THREAD

**Issue by jsoneaday** [ArweaveTeam/arweave-js#121]
This is a suggestion. I am building an arweave swift based api. In my transactions I may include data. There was an issue in my Merkle code which caused the data_root to be invalid. However the transaction still went through without error. I think this is wrong as a transaction that contains data should fail entirely if the data cannot be included.

**Comment by rosmcmahon** [comment]
Agreed, this would be a nice feature, however

1. this is not an issue for this repo - the arweave-js client - it belongs in the nodes, i.e. arweave repo
2.  it is not possible to implement there anyhow as it just wouldn't scale

Thanks for the suggestion though!
