### ISSUE TITLE
Error: Coudn't complete data download

### ISSUE THREAD

**Issue by luckyr13** [ArweaveTeam/arweave-js#132]
Hi! Today I updated the arweave-js version on my project and notice an issue in my dApp.

I have this TX: A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0

And I'm using getData to get the data from the tx:
`const data = await arweave.transactions.getData('A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0', {decode: true, string: true} );`

Before the update everything was fine, the data was fetched, but now I'm getting these errors from the console:

`[chunk] Failed to fetch chunk at offset 11882184452909`
`chunks.js:67 [chunk] This could indicate that the chunk wasn't uploaded or hasn't yet seeded properly to a particular gatway/node`
`Error: Error: Coudn't complete data download at 0/1563`

I think that maybe the problem comes from the offset calculation and the arweave-js new update.

Please help! haha. Thanks in advance :)

**Comment by hlolli** [comment]
If you take a look at
```
https://arweave.net/tx/A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0/offset
```

you can track down where the chunks for a give transaction is located at.

The offset ends at 11882184454471 but begins at 11882184454471 - dataSize + 1.
So it starts at: 11882184454471 - 1563 + 1 = 11882184452909

Now if you try to download that chunk
```
curl https://arweave.net/chunk/11882184452909
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Not Found</pre>
</body>
</html>
```

it seems it isn't found.

this transaction was mined into block 756664 at 26th of August 2021 (writing this as I'm thinking out loud).

And indeed it is visible from the gateway cache: https://an7bym2iyfh2bmjinrfqykwm5sdjrqwos6kdgn7buhj6ku2m6twq.arweave.net/A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0/

This means in simple terms, sadly, that the gateway received the chunks but didn't succeed in sending them to our nodes (that is a serious problem if true).

To verify this hypothesis: try to curl that chunk from peers in the network
https://arweave.net/peers

e.g. 
curl http://110.52.217.148:1984/chunk/11882184452909
curl http://220.200.166.227:1984/chunk/11882184452909
curl http://122.100.147.8:1984/chunk/11882184452909
curl http://52.199.181.113:1984/chunk/11882184452909

To fix this:
1. download the data and the transaction headers.
2. Run the following code snippet as is described in README.md

```js
const Arweave = require("arweave");
const ArweaveTransaction = require("arweave/lib/transaction.js");
const fs = require("fs");

const arweave = Arweave.init({
  host: "arweave.net",
  port: 443,
  protocol: "https",
});

let data = fs.readFileSync(
  "./data_from_the_gateway.ext"
);

let txHeaders = require("./tx_header.json"); 

(async () => {
  const tx = new ArweaveTransaction.default(resumeObject);

  let uploader = await arweave.transactions.getUploader(tx, data);

  while (!uploader.isComplete) {
    await uploader.uploadChunk();
  }

})();
``` 

feel free to replace

```js
const arweave = Arweave.init({
  host: "arweave.net",
  port: 443,
  protocol: "https",
});
```

with a node or gateway of your choosing (given that arweave.net likely failed here, but I'm sure it will work the second time).

Alternative to all of this, you can choose to fetch the data from the gateway-cache instead of relying on getData:

```js
const data = fetch("https://arweave.net/A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0");
```

since the gateway cache isn't permanent, I strongly encourage to re-upload the chunks to make fully sure the nodes have them!

We are planing to re-upload all the chunks in coming weeks, but until then, we can only be as good as our weakest link, and it seems we clearly made a mistake here.

**Comment by luckyr13** [comment]
Thank you! I can understand the problem now. It seems that the chunk is not present. I will try the proposed solution, thanks in advance for your fast reply!

**Comment by rosmcmahon** [comment]
> If you take a look at
> 
> ```
> https://arweave.net/tx/A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0/offset
> ```
> 
> you can track down where the chunks for a give transaction is located at.
> 
> The offset ends at 11882184454471 but begins at 11882184454471 - dataSize + 1. So it starts at: 11882184454471 - 1563 + 1 = 11882184452909
> 
> Now if you try to download that chunk
> 
> ```
> curl https://arweave.net/chunk/11882184452909
> <!DOCTYPE html>
> <html lang="en">
> <head>
> <meta charset="utf-8">
> <title>Error</title>
> </head>
> <body>
> <pre>Not Found</pre>
> </body>
> </html>
> ```
> 
> it seems it isn't found.
> 
> this transaction was mined into block 756664 at 26th of August 2021 (writing this as I'm thinking out loud).
> 
> And indeed it is visible from the gateway cache: https://an7bym2iyfh2bmjinrfqykwm5sdjrqwos6kdgn7buhj6ku2m6twq.arweave.net/A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0/
> 
> This means in simple terms, sadly, that the gateway received the chunks but didn't succeed in sending them to our nodes (that is a serious problem if true).
> 
> To verify this hypothesis: try to curl that chunk from peers in the network https://arweave.net/peers
> 
> e.g. curl http://110.52.217.148:1984/chunk/11882184452909 curl http://220.200.166.227:1984/chunk/11882184452909 curl http://122.100.147.8:1984/chunk/11882184452909 curl http://52.199.181.113:1984/chunk/11882184452909
> 
> To fix this:
> 
>     1. download the data and the transaction headers.
> 
>     2. Run the following code snippet as is described in README.md
> 
> 
> ```js
> const Arweave = require("arweave");
> const ArweaveTransaction = require("arweave/lib/transaction.js");
> const fs = require("fs");
> 
> const arweave = Arweave.init({
>   host: "arweave.net",
>   port: 443,
>   protocol: "https",
> });
> 
> let data = fs.readFileSync(
>   "./data_from_the_gateway.ext"
> );
> 
> let txHeaders = require("./tx_header.json"); 
> 
> (async () => {
>   const tx = new ArweaveTransaction.default(resumeObject);
> 
>   let uploader = await arweave.transactions.getUploader(tx, data);
> 
>   while (!uploader.isComplete) {
>     await uploader.uploadChunk();
>   }
> 
> })();
> ```
> 
> feel free to replace
> 
> ```js
> const arweave = Arweave.init({
>   host: "arweave.net",
>   port: 443,
>   protocol: "https",
> });
> ```
> 
> with a node or gateway of your choosing (given that arweave.net likely failed here, but I'm sure it will work the second time).
> 
> Alternative to all of this, you can choose to fetch the data from the gateway-cache instead of relying on getData:
> 
> ```js
> const data = fetch("https://arweave.net/A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0");
> ```
> 
> since the gateway cache isn't permanent, I strongly encourage to re-upload the chunks to make fully sure the nodes have them!
> 
> We are planing to re-upload all the chunks in coming weeks, but until then, we can only be as good as our weakest link, and it seems we clearly made a mistake here.

I wonder if it would be worth putting this into `advanced-readme.md` or something maybe?

**Comment by luckyr13** [comment]
Hello team, probably was only a one in a million case. My dApp is working great again haha thank you very much for your fast support. I did what @hlolli suggested me and now everything seems to work fine.  This was my final code:
```

const Arweave = require("arweave");
const ArweaveTransaction = require("arweave/node/lib/transaction.js");
const fs = require("fs");

const arweave = Arweave.init({
  host: "arweave.net",
  port: 443,
  protocol: "https",
});

let data = fs.readFileSync(
  "./txData.txt"
);

let txHeaders = require("./txHeaders.json"); 

(async () => {
  const tx = new ArweaveTransaction.default(txHeaders);

  let uploader = await arweave.transactions.getUploader(tx, data);

  while (!uploader.isComplete) {
    await uploader.uploadChunk();
  }

})();

```

Thanks again!

**Comment by rosmcmahon** [comment]
I did some digging around and came up with this, you can just feed it your txid 😃
```js
		const txid = 'A34cM0jBT6CxKGxLDCrM7IaYws6XlDM34aHT5VNM9O0'

		const { data } = await axios.get('https://arweave.net/' + txid, {
			responseType: 'arraybuffer',
		})

		const uploader =  await arweave.transactions.getUploader(txid, data)
		
		while(!uploader.isComplete){
			await uploader.uploadChunk()
			console.log(`chunkUploaded: ${uploader.uploadedChunks}/${uploader.totalChunks} %${uploader.pctComplete}`)
			console.log(`lastResponseStats: ${uploader.lastResponseStatus}`)
		}
```

**Comment by luckyr13** [comment]
Big thank you @rosmcmahon Arweave still has so many mysteries to me. Community here is awesome, thank you both! You saved a good man today 👍🏽

**Comment by charmful0x** [comment]
I'm still encountering this issue while using SmartWeave. Weird experience.

While using the following node code block, I try to read the state of the following contract: `e3f94a5pQrkoZHopWopR8vNFWDdrdt1uafxU1z8n6Yc` 

**Note: the contract has been deployed using SmartWeave CLI**

Node.js:
```js
import { readContract } from "smartweave";
import Arweave from "arweave";

const CONTRACT = "e3f94a5pQrkoZHopWopR8vNFWDdrdt1uafxU1z8n6Yc";
const arweave = Arweave.init({
  host: "arweave.net",
  port: 443,
  protocol: "https",
  timeout: 20000,
  logging: false,
});

export async function readRegistryContract() {
  try {
    const state = await readContract(arweave, CONTRACT);
    return state
  } catch(error) {
    console.log(error);
    process.exit(1);
  }
}

/** PACKAGE.JSON Dependencies
  * "dependencies": {
   * "arweave": "^1.10.23",
   * "redstone-smartweave": "^0.4.4",
    *"smartweave": "^0.4.46"
 * }
 
 **/
```
However, while running the code above, the following error is thrown:

![image](https://user-images.githubusercontent.com/77340894/150189232-e2d51fcc-0710-4479-95f5-13302bd95bed.png)

**BUT**
Using Smartweave-CLI to read the contract's state is a successful attempt:

![image](https://user-images.githubusercontent.com/77340894/150189691-f06c1ad7-ddf0-428c-b837-92764171b6ed.png)


The error was experienced also yesterday for this contract `_PB9p2qoS8XbnBXL5UwuH2AYTSWVD6tI5rYYvq5G_MA` but it's fine now.

**Comment by rosmcmahon** [comment]
i couldn't reproduce this using arweave.net. are you using some nodes directly?

**Comment by yasushisakai** [comment]
Hi, the same issue happened to me when I  was testing.

txid: `oYpB0tUDvYjphc_HxuFzzrrO4VVHozp7nmfFzCLZZ0E` (https://viewblock.io/arweave/tx/oYpB0tUDvYjphc_HxuFzzrrO4VVHozp7nmfFzCLZZ0E)

I confirm the file uploaded by visiting:
https://arweave.net/oYpB0tUDvYjphc_HxuFzzrrO4VVHozp7nmfFzCLZZ0E

but the `getData` API returns the same error shown above in this thread.

`https://arweave.net/tx/oYpB0tUDvYjphc_HxuFzzrrO4VVHozp7nmfFzCLZZ0E/offset`

gives me:

`{"size":"82","offset":"47767984578888"}`

which I should be able to access via,
https://arweave.net/chunks/47767984578807

but returns an 400 error. any clues?

**Comment by rosmcmahon** [comment]
@yasushisakai 
> I confirm the file uploaded by visiting: https://arweave.net/oYpB0tUDvYjphc_HxuFzzrrO4VVHozp7nmfFzCLZZ0E

unfortunately this only confirms that the data is _cached_ in the arweave.net gateway.

your data is not seeded to the actual arweave network nodes for whatever reason. that's what `getData` is telling you above.

I have taken the liberty of running the reseeding code snippet solution above against your tx. and recieved these messages:

```bash
checking oYpB0tUDvYjphc_HxuFzzrrO4VVHozp7nmfFzCLZZ0E ...
[chunk] Failed to fetch chunk at offset 47767984578807
[chunk] This could indicate that the chunk wasn't uploaded or hasn't yet seeded properly to a particular gatway/node
Error : Coudn't complete data download at 0/82 : Error: Coudn't complete data download at 0/82
    at Chunks.downloadChunkedData (/Users/ros/repo-personal/test-nodejs-harness/src/common/chunks.ts:77:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Transactions.getData (/Users/ros/repo-personal/test-nodejs-harness/src/common/transactions.ts:155:42)
    at async checkChunks (/Users/ros/repo-personal/test-nodejs-harness/src/ar-tx/reseed.ts:42:19)
    at async main (/Users/ros/repo-personal/test-nodejs-harness/src/ar-tx/reseed.ts:106:5)
reseeding using arweave.net cache oYpB0tUDvYjphc_HxuFzzrrO4VVHozp7nmfFzCLZZ0E ...
82 bytes found in arweave.net cache
chunkUploaded: 1/1 %100
lastResponseStats: 200
you might need to wait 5-20 minutes for your reseeded data to become available.
```

so as explained above in this issue, your data was not seeded in this case. 
as it was found in the arweave.net cache, this is probably due to an error at the time of posting to that gateway. 

i hope this helps

**Comment by rosmcmahon** [comment]
update & fyi:
```bash
checking oYpB0tUDvYjphc_HxuFzzrrO4VVHozp7nmfFzCLZZ0E ...
82 bytes stored in the network nodes
```
