### ISSUE TITLE
Consider switching to undici library for http requests

### ISSUE THREAD

**Issue by ppedziwiatr** [ArweaveTeam/arweave-js#134]
https://www.npmjs.com/package/undici

Simple benchmark:
![image](https://user-images.githubusercontent.com/84311757/148400225-bc8b1782-1549-4950-973a-65c7be0d4adc.png)

![image](https://user-images.githubusercontent.com/84311757/148400294-80ae9a73-dcaf-4242-940c-8ae11149081c.png)

That's 2x the difference...

**Comment by ppedziwiatr** [comment]
obviously just for the node.js env.

**Comment by ppedziwiatr** [comment]
Yup, just like I've expected - huge performance boost while loading SmartWeave interacitons for our "loot" contract - from ~61s on default arweave.js (with Axios underneath) to ~40s on undici 🚀 20s difference...

arweave.js/axios
![image](https://user-images.githubusercontent.com/84311757/148423999-493909ed-aeb6-48d3-829a-b6c4007a5f6a.png)
![image](https://user-images.githubusercontent.com/84311757/148424048-c2dee473-2e06-49eb-9dcb-9b2584fa2e97.png)

undici:
![image](https://user-images.githubusercontent.com/84311757/148424093-ab08f851-219d-4dc5-9113-d753889844ee.png)
![image](https://user-images.githubusercontent.com/84311757/148424129-25efebfc-4327-4991-8b47-ed14ac1d59b4.png)

**Comment by rosmcmahon** [comment]
it does not support the browser. axios is a good all-rounder. 

if you replaced axios with undici for nodejs, would you also replace it with something in the browser? are native browser fetch calls faster? 

the code base is already split with a custom solution supporting nodejs crypto and webcrypto, so it's not totally unreasonable to split it further - although the cypto-drivers could probably be replaced by a single external library ? - but that's off topic

**Comment by ppedziwiatr** [comment]
I believe the best solution would be to prepare an isomorphic-fetch, with undici as a library used by node (sth. similar to https://www.npmjs.com/package/isomorphic-fetch).
We will prepare sth. similar for our contracts sdk and will let you know if it works as expected. If it will, you could consider using it in arweave-js.

**Comment by ppedziwiatr** [comment]
maybe it could also speed up a bit https://github.com/ArweaveTeam/arweave-js/issues/128

**Comment by ppedziwiatr** [comment]
we've created https://github.com/redstone-finance/redstone-isomorphic (which has isomorphic version of fetch - uses undici for node and native fetch for web).
But I assume you're currently not interested in using this (and we've already created a wrapper for arweave-js in our SDK), so I'm closing this issue.
