### ISSUE TITLE
React Native compatibility

### ISSUE THREAD

**Issue by jazilzaim** [ArweaveTeam/arweave-js#136]
Can we use this library for a React Native app?

**Comment by stan-dot** [comment]
hi, how was this resolved?

**Comment by rosmcmahon** [comment]
hi @stan-dot, i believe contributor @elliotsayes had something working. there was something about needing to use external crypto libraries though? 

maybe you can check their github [https://github.com/elliotsayes](https://github.com/elliotsayes)
