### ISSUE TITLE
Arlocal on node.js [ECONNREFUSED]

### ISSUE THREAD

**Issue by michalko** [ArweaveTeam/arweave-js#137]
Hi, 
i want to run arweave transaction on nodejs locally with running arlocal. My arlocal run on http://localhost:1984/.
I initialized arweave as:

```
const arweave = Arweave.init({
  'host': 'localhost',
  'port': 1984,
  'protocol': 'http'
})
```
i'm seding transaction as:

```
let transaction = await arweave.createTransaction({ data: "pipka" })
await arweave.transactions.sign(transaction)
```

I'm getting:
```
(node:213) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1984
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:213) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
```

Does arweave with arlocal not work on node? Because i copypasted everything from https://edgeandnode.com/blog/developers-guide-to-arweave except the part that my code is in node, and tutorials on react.

Any suggestions would be very appreciated

Best!

**Comment by rosmcmahon** [comment]
most likely the root issue is that you need to supply a jwk wallet to those 2 functions when using nodejs. 
that error isn't too informative though. it definitely needs to be looked at. 

thanks for opening the issue! 💯

**Comment by michalko** [comment]
It works now. I changed
`
const Arweave = require('arweave/node');
`
to
`
const Arweave = require('arweave');
`
and it's working.

**Comment by michalko** [comment]
After all import wasn't the core issue. Core issue was that i was running arlocal from windows terminal like this:

![image](https://user-images.githubusercontent.com/232871/151713025-a8c306c2-49a4-430d-9ff8-ee72f10d0079.png)

and somehow that caused this error:
`
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1984
`

when i started arlocal from vscode terminal it somehow works. 
![image](https://user-images.githubusercontent.com/232871/151713093-09513105-88af-4e02-b62e-924e08d3267a.png)


I'm not sure what causes this issue on my laptop but i'm writing it if someone else has this in this future.

**Comment by rosmcmahon** [comment]
OK, i'm glad it all worked out. i'll close this issue. 

i'm guessing vscode is helping with the local networking stuff perhaps? i've noticed it does some stuff like that automatically - creating tunnels from remote machines, for example
