### ISSUE TITLE
txs that are in gateway cache and on graphql are not returned by getData

### ISSUE THREAD

**Issue by xloem** [ArweaveTeam/arweave-js#141]
I'm running into a similar error as #132 except the transactions I'm looking at are quite old and do not have offsets.

An example transaction is GEJSszMKteClrXm6U_VeQbXf3hnTNhGVlukrxDEymNM . The content of this transaction can be retrieved via https://arweave.net/GEJSszMKteClrXm6U_VeQbXf3hnTNhGVlukrxDEymNM , but https://arweave.net/tx/GEJSszMKteClrXm6U_VeQbXf3hnTNhGVlukrxDEymNM/offset unfortunately returns a 404. If I try to reupload the data using the code in #132, I receive an error that the transaction doesn't exist.

I got this transaction from https://arweave.net/graphql as the first result of this query:
```
        query {
           transactions(
             first: 2147483647
             owners: ["z_TqsbmVJOKzpuQH4YrYXv_Q0DrkwDwc0UqapRrE0Do"]
             tags: [
               { name: "Type", values: ["update-ref"] }
               { name: "Repo", values: ["Gitopia"] }
             ]
           ) {
             edges {
               node {
                 id
                 tags {
                   name
                   value
                 }
               }
             }
           }
        }
```

It seems quite strange to me that the tx is in graphql but not the http api.

**Comment by rosmcmahon** [comment]
The tx in question is not an L1 tx, but a bundled tx (dataItem).
These don't exist in the nodes, so `getData` cannot find them. Data bundles are an L2 application, a gateway unpacks dataItems and serves them similarly to regular txs, but with certain differences. 

GQL and the `bundledIn` field are your guide here:

```graphql
{
  "data": {
    "transactions": {
      "edges": [
        {
          "node": {
            "id": "GEJSszMKteClrXm6U_VeQbXf3hnTNhGVlukrxDEymNM",
            "bundledIn": {
              "id": "TkV7IzaeCPy2dGdVB0UDamwkFoI43TGSv_LfKmnpJ5U"
            }
          }
        },
        {
          "node": {
            "id": "TkV7IzaeCPy2dGdVB0UDamwkFoI43TGSv_LfKmnpJ5U",
            "bundledIn": null
          }
        }
      ]
    }
  }
}
```
I'm going to close this, as it's not really an arweave-js issue

**Comment by xloem** [comment]
Thank you.
