### ISSUE TITLE
Errors sent by the server are suppressed in the API class

### ISSUE THREAD

**Issue by jfbeats** [ArweaveTeam/arweave-js#144]
https://github.com/ArweaveTeam/arweave-js/blob/3dcf421bfb7d4b69eb2e7714c33db6c1adcad4f3/src/common/lib/api.ts#L48-L53
for the get and post endpoints. This leads to error messages being used as the return value as if requests were fulfilled correctly instead of interrupting the logic flow. For example, the `createTransaction` method can return an object with the string value `'{"status":400,"error":"Not Found: HTTPError: Response code 429 (Too Many Requests)"}'` for its reward and last_tx fields

**Comment by rosmcmahon** [comment]
sorry for the delay in getting to this. i haven't thought through the implications, but we could throw the error here instead, right?

**Comment by jfbeats** [comment]
Yes, we can remove the try/catch block entirely. the problem is that there are probably a few places where the error handling is done by testing the return value for an error status (for example `if (res.status != 200) {}`), and a few other places that are using their own try/catch blocks. The error is re-thrown (right after the snippet I shared) if no error status is returned by the server but having those two distinct behaviors creates conflicts on how the rest of the code should do error handling. It's possible to either:

Leave it like that. Everywhere the api is used would always have to test the response status code, independently of other error handling

Or, personally, I'd remove the try/catch block entirely and let the error propagate to the functions using the api. They would have to use their own catch blocks, in which they can test for the error codes that they are able to handle. The upside is that, when devs forget to handle errors, functions would just alt instead of wrongly inserting error messages as valid return results

**Comment by rosmcmahon** [comment]
yes, i've seen some weird instances of this occurring. for example, when creating a tx, and there's a network problem, the tx anchor property gets filled with a html string containing the error page 😄 not desirable!

i agree the try/catch should probably be removed, but the consequences of that action need to be fully tested. i.e. as many http request errors as possible should be emulated and added to unit tests

**Comment by rosmcmahon** [comment]
i think the error codes are used heavily when handling chunks for example

**Comment by rosmcmahon** [comment]
just reading this again. i think it's too late to start throwing these errors here at source - too much code to review and change. we should just check the return value in the relevant places where errors should be thrown and act accordingly. what do you think @jfbeats ?

**Comment by jfbeats** [comment]
I don't know how much of the codebase is at risk of letting error message slide as values, but if you say that the behavior was relied upon a lot internally, it would make sense to limit the scope of the fix to only the commonly used methods exposed by the module and their dependencies, and rethrowing new errors when the status code check fails

**Comment by rosmcmahon** [comment]
right, so since we have pivoted to using Fetch api, these returns make a lot more sense. `fetch` doesn't throw errors for resolved status numbers. you need to check for these yourself. i'm pretty sure this was actually some preparation done a long time ago by @arweave-kyle in order to make this switch to fetch.

**Comment by rosmcmahon** [comment]
`getPrice` & `getTransactionAnchor` will be fixed in v1.13.2
