### ISSUE TITLE
window is undefined in wallets.js getAddress() using Node version

### ISSUE THREAD

**Issue by EVERYTHINGING** [ArweaveTeam/arweave-js#147]
when running with node:

`const addr = await arweave.wallets.getAddress()`

window is undefined in wallets.js getAddress()

**Comment by DanMacDonald** [comment]
In node you must pass an instance of JWKInterface to `getAddress()` in order to have a wallet to derive the address from. Calling `getAddress()` with no parameters will result in this error.
