### ISSUE TITLE
Unable to sign transaction

### ISSUE THREAD

**Issue by AlexReed19** [ArweaveTeam/arweave-js#159]
Followed [this](https://edgeandnode.com/blog/developers-guide-to-arweave/) tutorial on arweave, and I can confirm arlocal is running. When I try to create a transaction, the console reads 
```Error: Error signing transaction: Error: Unable to upload transaction: 400, unknown
    at Object.sign (injected.ts:266:13)
    at async Transactions.sign (transactions.ts:208:1)
    at async createTransaction (App.js:19:1)
```

The line of code that throws the error is `let transaction = await arweave.createTransaction({ data: formData })`
 
Running node v16.15.1 and npm 8.11.0.

**Comment by rosmcmahon** [comment]
ArLocal is a locally running mock of an arweave gateway. It's not mainnet, so, while you can use your mainnet wallet in this local testnet, your real world balance won't be reflected locally. you need to mint winstons to your local wallet.

you can mint to your ArLocal wallet using something like:
```
await axios.get(`/mint/${address}/100000000000000000000`);
```
i think? you can get more info from the Textury team, who actually develop and maintain this software [https://textury.org/](https://textury.org/) the Arlocal repo is pretty barbones, best way to get support is on their [Discord](https://discord.gg/GtS2NzVAJG)
