### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by gvko** [ArweaveTeam/arweave-js#161]
Hey guys, I'm getting the above mentioned error when calling `arweave.transactions.sign(transaction, wallet)`.
I'm using `"arweave": "^1.11.4"`.

I've traced it down to L:191 in `arweave/node/lib/transaction.js`. 
The interesting thing is that all the commands passed in the array to the function on L:191 successfully execute, when I run the separately. So, that makes me think the function call `await (0, deepHash_1.default)([...])` is what fails.

**Comment by rosmcmahon** [comment]
i've seen this many times in the support discord. it has always ended up being one of your arguments not being defined.

**Comment by rosmcmahon** [comment]
i will close this issue for now, feel free to reopen it if you want :-)

**Comment by gvko** [comment]
Whoops, my bad. I was using the wrong wallet file. I was using a Solana wallet instead of the Arweave wallet. I fixed that, but now I'm getting the following error: `"Nodes rejected the TX headers"`.
Here's the log history of my requests:

```shell
Requesting: https://arweave.net:443/tx_anchor
Response:   tx_anchor - 200
Requesting: https://arweave.net:443/price/895
Response:   price/895 - 200
tx id:  Zk3gY9de8VZ3tmebm7SScqkJ2dwu0wytHwotB7KxShk
Requesting: https://arweave.net:443/tx
{
  status: 400,
  statusText: 'Nodes rejected the TX headers',
  data: { error: 'Nodes rejected the TX headers' }
}
```

**Comment by angrymouse** [comment]
Yeah, we definitely need to do some error refactor in arweave.js. Sometimes returns error with absolutely understandable description. I probably will do some testing and submit PR soon

**Comment by rosmcmahon** [comment]
> Yeah, we definitely need to do some error refactor in arweave.js. Sometimes returns error with absolutely understandable description. I probably will do some testing and submit PR soon

did you start this work?

**Comment by rosmcmahon** [comment]
could probably look at [this](https://github.com/ArweaveTeam/arweave-js/issues/183) at the same time

**Comment by rosmcmahon** [comment]
fixed in this branch https://github.com/ArweaveTeam/arweave-js/tree/fix-error-handling
will be the next patch release

**Comment by rosmcmahon** [comment]
https://github.com/ArweaveTeam/arweave-js/pull/204
