### ISSUE TITLE
what data format in Block data, how to decode it

### ISSUE THREAD

**Issue by zhangmaosen** [ArweaveTeam/arweave-js#163]
hi :
I use js to get block data, and server response to me like this:
<img width="766" alt="截屏2022-07-06 15 12 11" src="https://user-images.githubusercontent.com/1047603/177491408-e2ed75a9-6a76-422f-a89c-6feb6ebec742.png">
 
how to decode it, thx

**Comment by rosmcmahon** [comment]
are you using arweave-js? 

if not, this looks like an object? maybe you want to do something like: `JSON.stringify(object)` before writing to file?

**Comment by angrymouse** [comment]
not looks like valid json

**Comment by angrymouse** [comment]
what method exactly did you call to get it? also how do you write it in .json file?

**Comment by rosmcmahon** [comment]
no answer. i guess it was copied incorrectly. closing issue.
