### ISSUE TITLE
Expected data to be a string, Uint8Array or ArrayBuffer

### ISSUE THREAD

**Issue by cormacncheese** [ArweaveTeam/arweave-js#165]
When attempting to upload a file to `arlocal` in node.js I get the following error 

`Error: Expected data to be a string, Uint8Array or ArrayBuffer`

It looks like I am passing an ArrayBuffer:

```

const Arweave = require('arweave')
const arweave = Arweave.init({
  host: '127.0.0.1',
  port: 1984,
  protocol: 'http',
})

async function createTransaction(arrayBuffer: ArrayBuffer) {
    if (!arrayBuffer) return

    try {
      // generate test wallet
      const key = await arweave.wallets.generate()

      /* creates and sends transaction to Arweave */
      const transaction = await arweave.createTransaction({ data: arrayBuffer }, key)
      await arweave.transactions.sign(transaction, key)
      const uploader = await arweave.transactions.getUploader(transaction)

      /* upload indicator */
      while (!uploader.isComplete) {
        //
        await uploader.uploadChunk()
      }
      return transaction.id
    } catch (err) {
      console.log('createTransaction error: ', (err))
    }
  }
  
  const file = await admin.storage().bucket('my-bucket').file(filePath).download();
  // typecast to Array Buffer
  const ab = file as unknown as ArrayBuffer;

  const id = await createTransaction(ab)
```
  

What am I doing wrong?

**Comment by rosmcmahon** [comment]
Well, you've convinced typescript that is an ArrayBuffer, but it didn't seem to want to believe you 😅
No idea what this `admin` object is, but it looks like it's returning a bucket rather than a file?

**Comment by cormacncheese** [comment]
It's a [google cloud storage](https://cloud.google.com/nodejs/docs/reference/storage/latest) bucket which returns a DownloadResponse which [looks like an array buffer ](https://cloud.google.com/nodejs/docs/reference/storage/latest/overview.html#_google_cloud_storage_DownloadResponse_type) but I could be wrong

**Comment by rosmcmahon** [comment]
You know what, some of your code was cut off on my mobile screen. My bad. You could download this file locally to check it first?

**Comment by cedriking** [comment]
Hey @cormacncheese , I haven't used GCS with Arweave so not sure what is happening here. But, I also think this is related to not sending the right data type. 

You can always give a try to submit the tx to mainnet too, to see what happens. Should receive the same error message.

**Comment by rosmcmahon** [comment]
>  [looks like an array buffer ](https://cloud.google.com/nodejs/docs/reference/storage/latest/overview.html#_google_cloud_storage_DownloadResponse_type) 

is that a buffer inside of an array? `[ buffer ]` i would definitely take a look at what is being returned before passing to arweave-js. i think maybe Typescript is trying to help you, which is why you had to force it by using `as unknown`.

**Comment by cormacncheese** [comment]
destructuring the returned data and switching mainnet worked!

Kept getting a 410 error on `arlocal`
