### ISSUE TITLE
Failed to fetch chunk

### ISSUE THREAD

**Issue by timothyshen** [ArweaveTeam/arweave-js#166]
Hi, 
I know this has been answered in issues [123](https://github.com/ArweaveTeam/arweave-js/issues/132)
I have posted 6 transactions today trying to resolve the issue using both
`transaction.post(transaction)` and uploader in the example, but non of the two works
![image](https://user-images.githubusercontent.com/10960710/180093631-a51b12e7-6131-45c9-a29b-3aae51db7c4d.png)
This is the error message with uploader function. 
txn hash: TZTrMhF5-zpSyQJp3ZeyVSrT079PMzS1WVq2bB6HKCY
All the transaction went through and the uploader did return in the console but when calling getData I still get chunk error.

Thanks

After hours of testing and trying, I believe it is the issue with vite. With React or Next.js, the function is running perfectly fine.

**Comment by angrymouse** [comment]
Arweave.js works badly in vite enviroment (#167)

**Comment by timothyshen** [comment]
Actually the issue was data was not boardcasted to the network. Rare cases. All further transactions are in good state

**Comment by rosmcmahon** [comment]
issue resolved as i understand it, closing
