### ISSUE TITLE
Single bundle file Doesn´t work in HBS Express html files

### ISSUE THREAD

**Issue by HermesAteneo** [ArweaveTeam/arweave-js#176]
I have a Node Express + HBS server.
It return .hbs files like .html and it run locally

When I use the Single bundle .js file into my .hbs files, locally ocurrs errors.

For example, in your "Hello world" basic example, the log returned is a 404 text because your script is calling to   "myserver.com/info" directory.

```
    <script src="https://unpkg.com/arweave/bundles/web.bundle.js"></script>
    <script>
      const arweave = Arweave.init({});
      arweave.network.getInfo().then(console.log);
    </script>
```

**Comment by rosmcmahon** [comment]
if you are self-hosting you would need to specify the gateway like so:
```ts
const arweave = Arweave.init({
  host: 'arweave.net',
  port: 443,
  protocol: 'https',
})
```

**Comment by HermesAteneo** [comment]
Thanks @rosmcmahon 
That solved it.
