### ISSUE TITLE
How to know the data uploaded has been confirmed?

### ISSUE THREAD

**Issue by rubb1sh** [ArweaveTeam/arweave-js#178]
I found website viewblock.io/tx/{txid} have a status that have two kinds, pending and data storage. But arweave-js don't have a function to get this status. So my question is, how to know the data upload has been uploaded in ARweave blockchain totally, that means data can be retrieve and never lost.

**Comment by radekxrandom** [comment]
There is a method for it. It's [mentioned in the documentation](https://github.com/ArweaveTeam/arweave-js#get-a-transaction-status). It fetches the transaction status (aptly named `arweave.transactions.getStatus(status: string)`). The whole snippet:
```javascript
arweave.transactions.getStatus('bNbA3TEQVL60xlgCcqdz4ZPHFZ711cZ3hmkpGttDt_U').then(res => {
    console.log(res);
    // {
    //  status: 200,
    //  confirmed: {
    //    block_height: 140151,
    //    block_indep_hash: 'OR1wue3oBSg3XWvH0GBlauAtAjBICVs2F_8YLYQ3aoAR7q6_3fFeuBOw7d-JTEdR',
    //    number_of_confirmations: 20
    //  }
    //}
})
```
You can find more usage examples if you read [the tests](https://github.com/ArweaveTeam/arweave-js/blob/master/test/transactions.ts#L176)

**Comment by ppedziwiatr** [comment]
> I found website viewblock.io/tx/{txid} have a status that have two kinds, pending and data storage. But arweave-js don't have a function to get this status. So my question is, how to know the data upload has been uploaded in ARweave blockchain totally, that means data can be retrieve and never lost.

Remember to wait at least 10-15 confirmations. Or simply upload via Bundlr...

**Comment by rosmcmahon** [comment]
closing this as it seems answered.
