### ISSUE TITLE
Error while posting Transaction "Nodes rejected the TX headers"

### ISSUE THREAD

**Issue by soulsayer9029** [ArweaveTeam/arweave-js#182]
```
const transaction = await arweave.createTransaction({data:data}, wallet);
    transaction.addTag('D-Blog', process.env.APP_NAME as string)
    transaction.addTag('Content-Type', 'application/json');
    transaction.addTag('Address', address);
    console.log(transaction)
    const response=await arweave.transactions.post(transaction);
    console.log(response)
```

This is the code I am trying to run.I have done proper initialization and setup.What could be the reason for this error?

{
  status: 400,
  statusText: 'Nodes rejected the TX headers',
  data: { error: 'Nodes rejected the TX headers' }
}

**Comment by rosmcmahon** [comment]
Likely you are using a generated wallet without balance.
Please join [Arweave Dev Talk](https://discord.gg/8XFpc4Yt)  to discuss further.
