### ISSUE TITLE
Unable to use on Node

### ISSUE THREAD

**Issue by wolframeth** [ArweaveTeam/arweave-js#191]
I'm using CommonJS for the TS module and I'm getting this error:

```
/home/wolfjitsu/Documents/Projects/baste/src/services/arweave/arweave.service.ts:6
    this.arweave = Arweave.init({});
                           ^
TypeError: Cannot read properties of undefined (reading 'init')
    at new ArweaveService (/home/wolfjitsu/Documents/Projects/baste/src/services/arweave/arweave.service.ts:6:28)
    at new ServiceManager (/home/wolfjitsu/Documents/Projects/baste/src/services/manager.ts:22:45)
    at new App (/home/wolfjitsu/Documents/Projects/baste/src/app.ts:9:58)
    at Object.<anonymous> (/home/wolfjitsu/Documents/Projects/baste/src/app.ts:38:13)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/home/wolfjitsu/Documents/Projects/baste/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/home/wolfjitsu/Documents/Projects/baste/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
```
Importing the library is nothing out of the ordinary:
```
import Arweave from "arweave";

export class ArweaveService {
  arweave;
  constructor() {
    this.arweave = Arweave.init({});
  }
}
```

Any help would be greatly apprciated.

**Comment by rosmcmahon** [comment]
you need to manually specify a `host` when using nodejs. e.g.
```ts
const arweave = Arweave.init({
  host: 'arweave.net',
  protocol: 'https',
  port: 443,
})
```
you can get away without specifying `protocol` & `port` usually, but you seem to need them when call from JS as opposed to TS.

**Comment by rosmcmahon** [comment]
Have you installed arweave?

**Comment by mfig** [comment]
`import Arweave from 'arweave/node';`

**Comment by mfig** [comment]
@rosmcmahon thanks for you message, I encountered today the same problem as author. The project was created using [@nrwl/nest](https://nx.dev/packages/nest#nrwlnest)

In case someone else occurs the same issue I pasted my solution.

> for several years now, you can import like so:
> import Arweave from 'arweave'

I mean this was obviously the first thing I tried (I see that author used it as well).
However despite the code was compiling without issues, for some reason Arweave was undefined.

**Comment by rosmcmahon** [comment]
> @rosmcmahon thanks for you message, I encountered today the same problem as author. The project was created using [@nrwl/nest](https://nx.dev/packages/nest#nrwlnest)
> 
> In case someone else occurs the same issue I pasted my solution.
> 
> > for several years now, you can import like so:
> > import Arweave from 'arweave'
> 
> I mean this was obviously the first thing I tried (I see that author used it as well). However despite the code was compiling without issues, for some reason Arweave was undefined.

In that case, could you share some more information regarding the specifics of your environment? NodeJS version, arweave-js version, platform, etc. 
Many thanks for contributing!

**Comment by mfig** [comment]
Looks like the issue was me not restarting the dev server after adding `"esModuleInterop": true` (was required due to tslint error).

After saving the tsconfig file app restarted itself (webpack hot reload) but Arweave was imported as undefined.

Only when I manually rerun dev server Arweave is imported correctly. Sorry for bothering you @rosmcmahon

**Comment by rosmcmahon** [comment]
this is helpful information to know when troubleshooting! thanks for reporting back, much appreciated @mfig 😃
