### ISSUE TITLE
1.12.2 Using Not Defined Headers Class

### ISSUE THREAD

**Issue by IndreamLuo** [ArweaveTeam/arweave-js#194]
I got the following error with the newest `1.12.2` version packages.

```
ReferenceError: Headers is not defined
    at Api.request (/xxx/node_modules/arweave/node/lib/api.js:43:25)
    at Api.get (/xxx/node_modules/arweave/node/lib/api.js:29:27)
    at Wallets.getBalance (/xxx/node_modules/arweave/node/wallets.js:41:25)
```

I checked with the implementation. Seems like it's using fetch API (and expecting fetch.Headers) in the newest update.

Is `1.12.2` missing dependency of `fetch` in package?

**Comment by rosmcmahon** [comment]
What version of NodeJS are you using?

**Comment by IndreamLuo** [comment]
> What version of NodeJS are you using?

v16.15.1

**Comment by hackxhao** [comment]
I met the same problem.

**Comment by rosmcmahon** [comment]
ah dang, this is not working how i thought it was. thanks for reporting!
for now, you can either:

1. revert to arweave@1.11 
2. upgrade to nodejs@18
3. or specify in your startup script:

- for JS: `node --expermimental-fetch ...`
- for TS: `NODE_OPTIONS='--experimental-fetch' ts-node ...`

**Comment by rosmcmahon** [comment]
cc @martonlederer

**Comment by martonlederer** [comment]
Ahhh no... We might need to look into a nodejs fetch pkg anyway

**Comment by rosmcmahon** [comment]
> ah dang, this is not working how i thought it was. thanks for reporting! for now, you can either:
> 
>     1. revert to arweave@1.11
> 
>     2. upgrade to nodejs@18
> 
>     3. or specify in your startup script:
> 
> 
>     * for JS: `node --expermimental-fetch ...`
> 
>     * for TS: `NODE_OPTIONS='--experimental-fetch' ts-node ...`

i'm marking this as closed, with these as the solutions.

**Comment by VinceJuliano** [comment]
With node version 16.19.0 we get the headers is not defined issue -

ReferenceError: Headers is not defined

We don't get that issue with node 18.13

its looks like the required engine is 16.15.0 in package.json

This is with the latest arweave-js, thanks guys!

**Comment by rosmcmahon** [comment]
> With node version 16.19.0 we get the headers is not defined issue -
> 
> ReferenceError: Headers is not defined
> 
> We don't get that issue with node 18.13
> 
> its looks like the required engine is 16.15.0 in package.json
> 
> This is with the latest arweave-js, thanks guys!

in your case you can start your node v16 app by adding the `--experimental-fetch` flag. it's safe to add this flag to node v18+ apps too. 
if the warning is annoying, you can also add `--no-warnings`

**Comment by rosmcmahon** [comment]
I've updated the [Release Notes](https://github.com/ArweaveTeam/arweave-js/releases/tag/v1.12.4) for v1.12
