### ISSUE TITLE
Add support for multi-transaction update

### ISSUE THREAD

**Issue by JustMaier** [ArweaveTeam/arweave-js#21]
https://github.com/ArweaveTeam/arweave/issues/105 introduced support for multiple transactions given posted transactions reference the `last_tx` pulled from `/tx_anchor`. This package needs to pull the tx from the anchor and use that when posting transactions to full support multiple transactions per block.

**Comment by arweave-kyle** [comment]
Hey @JustMaier, good spot!

We're just trialing this feature a bit more before baking it into the JS library. We'll be updating this soon though! :rocket:

**Comment by aidanok** [comment]
This is implemented in recent versions of Js SDK / arweave-deploy and most community SDKs and so closing this.
