### ISSUE TITLE
Error in `transactions.getData` Function with Sveltekit

### ISSUE THREAD

**Issue by omerharuncetin** [ArweaveTeam/arweave-js#213]
Hello,

I am trying to get transaction data by using `tx id`. I installed arweave package and created my arweave instance.

```js
import Arweave from 'arweave';
const arweave = Arweave.init({});
```

I  created a function to get transaction data.

```ts
export const getArweaveData = async (txId: string): Promise<Metadata> => {
	const result = await arweave.transactions.getData(txId, {
		decode: true,
		string: true,
	});

	console.log('result is here');

	if (typeof result === 'string') {
		return JSON.parse(result);
	}
	throw new Error('Arweave result type is not in proper format!');
};

```

When I call this function it gives me an error first but also returns the value correctly. Here are the errors:

### Errors
- GET https://arweave.net/tx/zRyF_n-EPmumk5JQVwyCQ0XQd8bDOnqWKoBOo_L4fU0/offset 404
- transactions.js:97 Error while trying to download chunked data for zRyF_n-EPmumk5JQVwyCQ0XQd8bDOnqWKoBOo_L4fU0
g
- Error: Unable to get transaction offset: unknown
    at Chunks.getTransactionOffset (chunks.js:15:15)
    at async Chunks.downloadChunkedData (chunks.js:33:32)
    at async Transactions.getData (transactions.js:94:20)
 

Also, the function gives me the data correctly at the end. But because of the errors, the application does not work properly. 

Here are the details about the configuration and systems:

- I am using Svelte with Sveltekit `1.0.0-next.196`
- I installed the arweave package with  version `1.13.7`

**Comment by rosmcmahon** [comment]
Thanks for the detailed issue!

So, I can see what's happening here. It's not actually related to svelte in this case. We generally don't advise people use `getData`, and here is a classic reason why. `getData` attempts to retrieve the low level chunks and reconstruct a base layer transaction from them. There's a fallback to use the gateway cache built in.

The tx you are retrieving is **not** a base layer tx, it's actually a bundled dataItem, as you can verify here
https://viewblock.io/arweave/tx/zRyF_n-EPmumk5JQVwyCQ0XQd8bDOnqWKoBOo_L4fU0

I would recommend that you instead use `arweave.api.get`, this goes directly to the cache, where your dataItem, in it's unbundled form, is accessible.

**Comment by omerharuncetin** [comment]
> 

Thank you this solved my issue 🙌
