### ISSUE TITLE
Parsable language to write arql queries in

### ISSUE THREAD

**Issue by mkg20001** [ArweaveTeam/arweave-js#22]
It would be cool if there would be a parsable language for arql so I could write one as a string instead of using nested objects

I've written some code down here: https://gist.github.com/mkg20001/42a252f5fdc0a27d4ff3ed055edaf2cb

Implemented examples: `& (= a 'test') (= b 'test')` and `and(equals(a, 'test'), equals(b, 'test'))`

Since both would use the same lexer (the lexer is actually not written yet), they could be both supported simultaniously.
Both token parsing functions return arql queries.

So far I've only implemented them to support `and` and `equals`
How should those query languages be implemented in arweave?

**Comment by mkg20001** [comment]
In order to avoid injections, I've thought of making special placeholder "variables" like `$1`, which will later be replaced by the values in a parameters array.
So one would do `arql({lang: '1'}, 'and(equals(a, $1), equals(b, $2)', [someVar, someOtherVar])`

**Comment by mkg20001** [comment]
I've implemented both in npm.im/arlang

Here's an example of it being in-use https://github.com/mkg20001/arweb/blob/master/src/static/arweave.js#L20

**Comment by arweave-kyle** [comment]
Hey @mkg20001 this is neat, we also enabled GraphQL recently on the /arql endpoint, have you tried it out? The /arql endpoint still serves the original arql syntax so both are compatible and will be for the foreseeable future :)

**Comment by mkg20001** [comment]
No, although arql fits my usecase just fine.
Could the arlang package possibly be mentioned somewhere?

**Comment by cedriking** [comment]
Hey @mkg20001 , did you see the amazing work @aokisok built to work with ArQL easier using a tiny library that creates the details for you while using simple functions: https://github.com/aokisok/arql-ops . Maybe this is something you're looking for.

**Comment by mkg20001** [comment]
It's pretty cool

I'm going to replace a part of my code that uses this, the other parts will likely continue to use arlang for where user-supplied queries are expected as strings

**Comment by aidanok** [comment]
Closing this as there now two libraries available that do this and are listed in the arweave-js docs :)
