### ISSUE TITLE
Switch from XMLHttpRequest to window.fetch

### ISSUE THREAD

**Issue by mkg20001** [ArweaveTeam/arweave-js#23]
It's no longer recommended and it's not supported in service workers, so it makes sense to move to window.fetch

**Comment by arweave-kyle** [comment]
Hey @mkg20001 we use [axios](https://github.com/axios/axios) currently so don't specifically manually implement XMLHttpRequest. We could replace axios and move to window.fetch but the current library works for nodejs and browsers, so this would need some additional work I think.

Out of curiosity what was the use case for service workers you had in mind? Might be worth looking at separate packages for each runtime so we can make each one a bit lighter, with less isomorphic code.

**Comment by mkg20001** [comment]
Hi,

Node:
```js
const fetch = require('node-fetch')
```

Browsers:
```js
if (!window.fetch) {
  require('whatwg-fetch')
}

const fetch = window.fetch
```

It works for both, if you know the libs.

**Comment by mkg20001** [comment]
> Out of curiosity what was the use case for service workers you had in mind? Might be worth looking at separate packages for each runtime so we can make each one a bit lighter, with less isomorphic code.

The usecase was to make an arweave-based "backend" that accesses arql using a service worker to make it possible to write apps as if there was a backend.

The current arweave library has all the features this requires and most of them are needed so making a seperate library doesn't make that much sense.
I'd rather use the fetch API on nodeJS and browsers, since it's a lot less complex then most request libraries and is the recommended way of fetching things in the browser.

**Comment by arweave-kyle** [comment]
Hey @mkg20001 changing the underlying library will cause some cascading issues as anything that interacts with the underlying axios responses will break, so we can change this but it would have to be in the next major so I'm not sure just yet when that will be.

**Comment by mkg20001** [comment]
Ok

I'm currently using my own shim, which does arweave requests via fetch and only uses arweave.js for the crypto
