### ISSUE TITLE
Uploaded files sometimes cannot be downloaded.

### ISSUE THREAD

**Issue by a-fish-cannot-swim** [ArweaveTeam/arweave-js#235]
When testing locally, sometimes larger uploaded files (e.g., over 100MB) cannot be downloaded. The request initiated by this line of code in web.bundle.js: const resp = await this.api.get('chunk/${offset}'); keeps returning a 403 error. What could be the reason for this?

**Comment by rosmcmahon** [comment]
sounds weird. are you using ArLocal, a node, or one of the gateways? any txid?

**Comment by a-fish-cannot-swim** [comment]
> sounds weird. are you using ArLocal, a node, or one of the gateways? any txid?听起来很奇怪。您使用的是 ArLocal、节点还是其中一个网关？任何 txid？

Thank you for the reply. The server is deployed on a single node locally and is not connected to your production environment. Sometimes the uploaded files can be downloaded, but at other times, the request initiated by the above-mentioned line of JavaScript code (const resp = await this.api.get('chunk/${offset}');) results in a 403 error, and the file cannot be downloaded.

**Comment by rosmcmahon** [comment]
yeah, i've never heard of that happening to anyone tbh. _**it's not an issue with arweave-js,**_ either:

1. you have some strange network configuration on your local machine
2. there's something misconfigured on the arweave node

i notice you already have an open issue in the arweave node repo (https://github.com/ArweaveTeam/arweave/issues/645) i suggest you continue troubleshooting there.

closing this as not related to arweave-js, thanks
