### ISSUE TITLE
Way to directly get transaction data

### ISSUE THREAD

**Issue by mkg20001** [ArweaveTeam/arweave-js#24]
Currently one needs to get the transaction first and then get the data. It would be cool if there would be a single method to just get the data based on the transaction id.

**Comment by arweave-kyle** [comment]
Hey @mkg20001 this is already supported, you can use the `tx/:id/data` endpoint which will just serve you the data field from the transaction. Happy hacking!

**Comment by mkg20001** [comment]
Is there a method in this package? I was specifically asking about a method in this package, not arweave itself

**Comment by cedriking** [comment]
Hey @mkg20001 I did a few important updates to `arweave-js`, this will allow us to work on the source code on Windows without problems. 

I also added this method to the same PR. I think it's an important function to have without having to get the entire transaction.

PR: https://github.com/ArweaveTeam/arweave-js/pull/26

**Comment by mkg20001** [comment]
Just what I need

When's that going to be released?

**Comment by arweave-kyle** [comment]
Hey @mkg20001 these changes have been merged now. Docs here https://github.com/ArweaveTeam/arweave-js#get-transaction-data 😄
