### ISSUE TITLE
Submit transaction with unsigned

### ISSUE THREAD

**Issue by septs** [ArweaveTeam/arweave-js#36]
```
Requesting: https://arweave.net:443/tx
{
  status: 500,
  statusText: 'Internal Server Error',
```

If submit transaction is unsigned then throw error?

**Comment by aidanok** [comment]
Hey @septs, yep transactions need to be signed before they are posted to /tx endpoint

**Comment by septs** [comment]
@aidanok  I think you should check for signatures when submitting transaction.

**Comment by septs** [comment]
https://github.com/ArweaveTeam/arweave-js/blob/8e122a682ab05c4e2e81a5b25bc75465815beb04/src/common/transactions.ts#L197-L203

**Comment by aidanok** [comment]
Ah, I see what you mean, yes this a good point. 

We could do more checks to ensure it's a valid transaction and error early with a clear message.
