### ISSUE TITLE
Sign transactions on creation if a key is passed.

### ISSUE THREAD

**Issue by arweave-kyle** [ArweaveTeam/arweave-js#5]
Transactions from createTransaction and createSiloTransaction should be signed by default as they can be signed again if the consuming application wants to modify the contents, add tags etc before submitting.

**Comment by rosmcmahon** [comment]
Perhaps this should be added just before posting to avoid duplication of work? As it happens, there is new signAndPost function in the pipeline that will do this.

Closing this issue for now.
