### ISSUE TITLE
GraphQL Library & Support

### ISSUE THREAD

**Issue by TheLoneRonin** [ArweaveTeam/arweave-js#56]
### Description

Integrating a chainable, function based library for interfacing with Arweave's GraphQL library would be a great feature to have for the project. The following are a proposed implementation for interfacing with GraphQL.

#### Initializing a GraphQL query

```typescript
const arweave = Arweave.init({ ... });
const result = await arweave.query({ ...options }); // Initializes a new query
```

#### GraphQL options

```typescript
arweave.query({
  // Default has the full GraphQL object
  output: `{
     cursor
     node {
        ...
     }
  }`,
});
```

#### Select by Tag

```typescript
arweave
  .query()
  .tag({
    name: 'name',
    values: ['values'],
    sort: 'ASC',
  })
  .tag({ ... }); 
```

#### Limit and After

```typescript
arweave
  .query()
  .after('cursor')
  .limit(10);
```

#### Sort by block height

```typescript
arweave
  .query()
  .sort('ASC');
```

#### Block range

```typescript
arweave
  .query()
  .blocks({ min: 0, max: 10 });
```

#### Owners

```typescript
arweave
  .query()
  .owners([...addresses]);
```

### Recipients

```typescript
arweave
  .query()
  .recipients([...addresses]);
```

### By block ID

```typescript
arweave
  .query()
  .blockId([...]);
```

**Comment by t8** [comment]
Fully support this, though I'm not sure this is something that necessarily *has* to be a part of ArweaveJS. I can say that we'd definitely appreciate its addition to the library though (one less dependency)!

If this were to be implemented here, do you think it would make more sense to be accessed via `arweave.transactions.query()` instead?

**Comment by TheLoneRonin** [comment]
It could absolutely be rolled as a plugin.
However, I think the `SLOC` would be low enough that it being part of core would be perfectly okay!

The library being part of `arweave.transactions` makes a lot of sense to me! 💯

**Comment by CDDelta** [comment]
I disagree with this. Interfacing with the Arweave GraphQL API isn't very hard with the right tools.

With a little configuration of a GQL code generator like [this](https://graphql-code-generator.com/), you can take advantage of the type-safety, field specificity, and autocomplete GraphQL and all its other tooling offers.

Perhaps this should just be documented better? 🤔 😄

**Comment by t8** [comment]
The utility isn't necessarily for making writing queries *easier* per say. Rather, it would a way for developers to query GraphQL with built-in tools. Or, at least, that is why I'm in favor of this proposal.

Additionally, I'm not attracted to hardcoding the gateway. Pulling this data from the current Arweave instance could allow for dynamic gateway switching in the future. Not sure if/what @TheLoneRonin's plans were for this. I suppose someone could still do all of this manually, but at the very minimum, building the `query` function and supporting the GraphQL object appeals to me the most.

Regarding documentation: @TheLoneRonin actually published a very well-written and comprehensive docs site for exactly this! You can find it [here](https://gql-guide.vercel.app/).

As a workaround to native arweave-js implementation, @johnletey created a super useful library for querying GraphQL by simply providing the query object: https://github.com/johnletey/arGQL

**Comment by CDDelta** [comment]
> Additionally, I'm not attracted to hardcoding the gateway. Pulling this data from the current Arweave instance could allow for dynamic gateway switching in the future. Not sure if/what @TheLoneRonin's plans were for this. I suppose someone could still do all of this manually, but at the very minimum, building the `query` function and supporting the GraphQL object appeals to me the most.

I'm not sure I entirely follow you here. Are you referring to having the result of the GQL query change at runtime depending on the gateway schema? I think a great benefit of GraphQL is that query results changing is checked for and protected against. I guess we just have different project goals 😅 

> Regarding documentation: @TheLoneRonin actually published a very well-written and comprehensive docs site for exactly this! You can find it [here](https://gql-guide.vercel.app/).

I was more referring to documentation directing/instructing devs on setting up a GraphQL code generator. I love having type-safety with my queries and I think more people should use it. The code generator can also be configured to generate a client object which you use to perform all your queries. It's awesome.

> The utility isn't necessarily for making writing queries _easier_ per say. Rather, it would a way for developers to query GraphQL with built-in tools. Or, at least, that is why I'm in favor of this proposal.

This makes sense. Having it built into the SDK certainly makes things easier to start with. I'm just not sure it would be a scalable approach in the long term for larger projects or a more complex gateway schema.

**Comment by t8** [comment]
> I'm not sure I entirely follow you here. Are you referring to having the result of the GQL query change at runtime depending on the gateway schema? I think a great benefit of GraphQL is that query results changing is checked for and protected against. I guess we just have different project goals 😅

Sorry for the vagueness! I was referring to Arweave gateways. Ex: If `arweave.net` goes offline temporarily, switch to `perma.online` or something like this. 

> I was more referring to documentation directing/instructing devs on setting up a GraphQL code generator. I love having type-safety with my queries and I think more people should use it. The code generator can also be configured to generate a client object which you use to perform all your queries. It's awesome.

Ahh, I see what you mean. Fair enough!

**Comment by TheLoneRonin** [comment]
> Perhaps this should just be documented better?

I agree! So I have a baseline guide here: https://gql-guide.vercel.app
But, augmenting it even further with GraphQL code generators + interactions with Arweave.

@CDDelta, I would love feedback on the best approach (or approaches) to interacting with Gateway GraphQL's.

Thanks for chiming in!
