### ISSUE TITLE
[Bug] Compilation error in Angular 11

### ISSUE THREAD

**Issue by demo-hub** [ArweaveTeam/arweave-js#59]
**Description**

I was just trying out this package with Angular and when I installed the package it gave me a compilation error after the code example that is on your README. 

![image](https://user-images.githubusercontent.com/42657824/101629296-09ec3300-3a19-11eb-91c2-24dc3c0b3c32.png)

**Code**

![image](https://user-images.githubusercontent.com/42657824/101629339-1b353f80-3a19-11eb-98db-553dcc07a04e.png)

![image](https://user-images.githubusercontent.com/42657824/101629581-7f580380-3a19-11eb-8795-20bf3a418907.png)

**Proposed solution**

So I went to see the source code and changed the static init: (apiConfig: ApiConfig) => Arweave; to static init: (apiConfig:? ApiConfig) => Arweave; and everything worked as intended.

I don't know if this is the expected behavior but I don't think it is because you refer in your documentation that the init function can be called without parameters and it seems to be working if you change the parameter to optional. Also, you should change your docs in the npm web section to import Arweave from 'arweave/web' instead of import Arweave from 'arweave'.

**Comment by cedriking** [comment]
Hello, Arweave allows an empty options object. So for the web, what will work is:
```js
import Arweave from 'arweave';
const arweave = Arweave.init({});
```
