### ISSUE TITLE
Tests not passing for Transactions and Silo Web

### ISSUE THREAD

**Issue by bidetaggle** [ArweaveTeam/arweave-js#64]
Hello, when I'm doing `npm run test:web` my browser open `web.html` and Transactions and Silo Web tests don't pass.

![Screenshot 2021-01-08 at 12 30 12](https://user-images.githubusercontent.com/7074019/104011026-b999f980-51ad-11eb-94fe-acba9461ac57.png)

Am I doing something wrong?

**Comment by rosmcmahon** [comment]
the Silo tests have since been fixed. thanks for the issue!
