### ISSUE TITLE
Bug with 'undefined' salt length 

### ISSUE THREAD

**Issue by alexander-morris** [ArweaveTeam/arweave-js#78]
![image](https://user-images.githubusercontent.com/37120777/108599823-cf343e80-7369-11eb-9888-0f46cd2ee551.png)

**Comment by Abhimanyu121** [comment]
Hey did anyone find any solution for this bug?

**Comment by cedriking** [comment]
Upgrading NodeJS to the latest version solves this issue 👍🏼
