### ISSUE TITLE
Bug with getUploader API

### ISSUE THREAD

**Issue by Xaber20110202** [ArweaveTeam/arweave-js#81]
https://github.com/ArweaveTeam/arweave-js/blob/92d690a52ed0b647f36d58a6eba28542ef609b18/src/common/transactions.ts#L347

When I pass the transaction ID to the getUploader method, the data gets the transaction information through the `get` API, but the returned upload data without the chunks field.

This causes the chunks check to not pass `fromSerialized`, so it will throw an error named `Transaction chunks not prepared`

**Comment by rosmcmahon** [comment]
i believe this issue may be resolved now. Can you check again?

**Comment by rosmcmahon** [comment]
no further issues being reported since previous fixes on uploader. marking as closed
