### ISSUE TITLE
A suggestion that we need serializeUploader and deserializeUploader API

### ISSUE THREAD

**Issue by Xaber20110202** [ArweaveTeam/arweave-js#82]
We need these two util functions, to make it easier to assemble and store uploader data. Currently, neither `JSON.stringify` nor `serialize-javascript` can restore the uploader in its entirety, causing the continuation upload to fail.

**Comment by rosmcmahon** [comment]
Pretty sure all issues related to the uploader have now been fixed. Please check again?

**Comment by rosmcmahon** [comment]
no further issues reported with uploader since fixes. marking this as resolved
