### ISSUE TITLE
TX_NOT_FOUND error for valid tx

### ISSUE THREAD

**Issue by AndreVallestero** [ArweaveTeam/arweave-js#86]
Doing
```javascript
arweave.transactions.getData(
  "8tqZAMa4w_tlzkaNba8lyo2-gY6qQ8TYk_6A7yxOzfE",
  { decode: true, string: true }
);
```
results in `TX_NOT_FOUND` error even though tx exists: https://arweave.net/tx/8tqZAMa4w_tlzkaNba8lyo2-gY6qQ8TYk_6A7yxOzfE

**Comment by cedriking** [comment]
Hey there 👋. It's not recommended to use getData anymore. It's best to use the `/txid` endpoint. Or you can use `arweave.api.get(txids);` which does the same thing. 

Cheers 🙌

**Comment by AndreVallestero** [comment]
Same issue
```javascript
  const bundledTrafficLogsResp = await arweave.api.get(8tqZAMa4w_tlzkaNba8lyo2-gY6qQ8TYk_6A7yxOzfE, {
    responseType: "arraybuffer"
  });
```

**Comment by cedriking** [comment]
Hey @AndreVallestero , we will continue the support of this issue via Discord (you already asked there), since it's not related to ArweaveJS.
