### ISSUE TITLE
A suggestion that maybe we can use webcrypto node API to replace crypto-browserify

### ISSUE THREAD

**Issue by Xaber20110202** [ArweaveTeam/arweave-js#90]
Currently that node support a [webcrypto API](https://nodejs.org/api/webcrypto.html)

So, we can get rid of the usage of  crypto-browserify package

**Comment by rosmcmahon** [comment]
as this is still experimantal as of node 17, and arweave-js supports down to v12, this dependency will not be updated for a while i imagine. thanks for the issue!
