### ISSUE TITLE
[Bug] The saltLength parameter of the sign method is invalid

### ISSUE THREAD

**Issue by Xaber20110202** [ArweaveTeam/arweave-js#91]
https://github.com/ArweaveTeam/arweave-js/blob/92d690a52ed0b647f36d58a6eba28542ef609b18/src/common/lib/crypto/webcrypto-driver.ts#L51

The saltLength parameter of the sign method is invalid.

And why does the verify method, which validates both saltLength 0 and saltLength 32, not accept the saltLength argument?

**Comment by rosmcmahon** [comment]
i believe this has since been fixed

**Comment by rosmcmahon** [comment]
stale. closing
