### ISSUE TITLE
what is the meaning overspend{     "status": 410,     "error": "overspend" }

### ISSUE THREAD

**Issue by malingzhao** [ArweaveTeam/arweave-js#92]

**Comment by mcmonkeys1** [comment]
usually it means there was not enough AR on the wallet at the time

**Comment by malingzhao** [comment]
I have 0.05 ar , And I transfer 0.01

**Comment by malingzhao** [comment]
I found the erlang code 

validate_overspend(TX, Wallets) ->
	From = ar_wallet:to_address(TX#tx.owner),
	Addresses = case TX#tx.target of
		<<>> ->
			[From];
		To ->
			[From, To]
	end,
	lists:all(
		fun(Addr) ->
			case maps:get(Addr, Wallets, not_found) of
				{0, Last} when byte_size(Last) == 0 ->
					false;
				{Quantity, _} when Quantity < 0 ->
					false;
				not_found ->
					false;
				_ ->
					true
			end
		end,
		Addresses
	).

**Comment by malingzhao** [comment]
Does the code use the online signature , and the privKey is on the machine And It is not offline

**Comment by malingzhao** [comment]
how do I use the offline signature

**Comment by mcmonkeys1** [comment]
Please come to the Discord chat server where we can try and troubleshoot your issue(s), thanks!
https://discord.gg/NWm9tTeY

**Comment by malingzhao** [comment]
ok
