### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by DeveloperInProgress** [ArweaveTeam/arweave-js#94]
I'm using ArweaveJS in Node. 

I did the initialization like this:

```
const Arweave = require('arweave/node');

const arweave = new Arweave.init({
            'host':'127.0.0.1',
            'port':1984,
            'protocol':'http'
        });
```

But I keep getting this error:

![image](https://user-images.githubusercontent.com/40036742/126689431-1abafc8c-aa73-4942-a434-5e8d132d5e8f.png)

All i'm trying to do is follow what is given in README to get started with arweave js. What I am doing wrong and How may I rectify it?

**Comment by hlolli** [comment]
Does replacing `127.0.0.1` with `arweave.net` work? The readme can be misleading, but 127.0.0.1 is not a valid public ip address, only as internal local address.

**Comment by DeveloperInProgress** [comment]
hi @hlolli! 
![image](https://user-images.githubusercontent.com/40036742/126691635-7cbafafa-db3a-4827-9b38-27e954029cdd.png)

**Comment by cedriking** [comment]
Hello, unless you have a local node running, you will need to connect to an online gateway, the most popular being arweave.net:

```js
const Arweave = require('arweave');
const arweave = new Arweave.init({
  'host': 'arweave.net',
  'port': 443,
  'protocol':'https'
});
```
