### ISSUE TITLE
[Bug] [typo] in type interface

### ISSUE THREAD

**Issue by DougAnderson444** [ArweaveTeam/arweave-js#98]
https://github.com/ArweaveTeam/arweave-js/blob/80c45858353c07e92c9598606719979eebbc1e9b/src/common/network.ts#L4

![image](https://user-images.githubusercontent.com/6699901/131216569-c7fd1b14-1ec3-4874-88e9-b2765849a424.png)

Is this supposed to be 

`network` 

instead of [misspelled, misnamed] 

`hosnetworkt`

?

**Comment by rosmcmahon** [comment]
yeah, it looks like there's something wrong there!
