### ISSUE TITLE
Show transection fee

### ISSUE THREAD

**Issue by Licini** [ArweaveTeam/arweave-js#99]
Greetings, is there way to show the cost of a transection before posting with arweave-js?  Thanks!

**Comment by mcmonkeys1** [comment]
Indeed, after creating the transaction you can check the reward field. E.g.:
``
const tx = await arweave.createTransaction({ data: "stuff" }, jwk)

console.log(tx.reward)
tx.reward += 10000
console.log(tx.reward)

await arweave.transactions.sign(tx, jwk)
``
etc.
